name: Python Package using Conda

on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        python a.py
